name: DeinWerbung
main: bz.dcr.werbung.Main
version: 0.2
author: Minedroid
commands:
  werbung:
    description: Werbetext buchen.
    usage: /werbung <Text>
    aliases: [w]
permissions:
  werbung.start:
    description: Starte eine Werbung
    default: true
  werbung.color:
    description: Farbcodes in Werbetexten nutzen
    default: true